version: '3.8'
services: 
  database:
    image: mongo
    volumes: 
      - my_data:/data/db 
    restart: always

    #see .env file 
    #environment: 
      #MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      #MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  node-app:
    image: node:16
    command: npm run dev
    #command: node server.js
    working_dir: /app
    #made on line 24
    depends_on: 
      - database
    volumes: 
      - ./Node-Blog-App:/app
    ports: 
      - "3000:3000"
    restart: always
    environment: 
      USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DB_HOST: database:27017 
      #see mongoose connect server.js file 
 
volumes: 
  my_data: 